### ISSUE TITLE
Persistent data is not working. So I cannot restart my home bridge.  

### ISSUE THREAD

**Issue by p000** [ikalchev/HAP-python#135]
```
INFO:pyhap.accessory_driver:Loading Accessory state from `data`
Traceback (most recent call last):
  File "D:/Projects/OnGoing/viper/temp.py", line 192, in <module>
    driver.add_accessory(accessory=get_bridge(driver))
  File "D:\Projects\OnGoing\viper\venv\lib\site-packages\pyhap\accessory_driver.py", line 330, in add_accessory
    self.load()
  File "D:\Projects\OnGoing\viper\venv\lib\site-packages\pyhap\accessory_driver.py", line 445, in load
    self.encoder.load_into(fp, self.state)
  File "D:\Projects\OnGoing\viper\venv\lib\site-packages\pyhap\encoder.py", line 78, in load_into
    state.private_key = ed25519.SigningKey(fromhex(loaded['private_key']))
  File "D:\Projects\OnGoing\viper\venv\lib\site-packages\ed25519\keys.py", line 85, in __init__
    vk_s, sk_s = _ed25519.publickey(sk_s)
MemoryError
```

**Comment by ikalchev** [comment]
What's the version of HAP-python and python that you are using?

**Comment by p000** [comment]
HAP-python (2.2.2)

**Comment by cdce8p** [comment]
Are you using Windows?

Those other issues could be helpful
https://github.com/warner/python-ed25519/issues/11
https://github.com/home-assistant/home-assistant/issues/13560

**Comment by p000** [comment]
Yes I'm using windows

**Comment by ikalchev** [comment]
What about the python version?

**Comment by p000** [comment]
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by schinckel** [comment]
I've got a fair bit of code sitting on top of HAP-python, and something at some point meant that it was no longer loading the data correctly, showing the same problem as p000. But it's entirely possible that was just a problem with my custom encoder.

(I'm using a bridge too, as it turns out, but not Windows).

**Comment by carlos-leopoly** [comment]
Same issue here:

Windows platform running in Python virtual environment:

**Home Assistant release with the issue:**
0.76.2
**Last working Home Assistant release (if known):**
**Operating environment (Hass.io/Docker/Windows/etc.)**
Windows
Windows 10 running python 3.6.5
**Component/platform:**
HomeKit, https://www.home-assistant.io/components/homekit/


Let me know if you need any additional data

**Comment by carlos-leopoly** [comment]
Additional info: Setup goes well and everything is well usable until restarting HA.
First I had 131 devices then I reduced to 57 by filters but same issue appeared
