### ISSUE TITLE
zeroconf.NonUniqueNameException

### ISSUE THREAD

**Issue by sderuiter** [ikalchev/HAP-python#186]
Hi,

My setup: 
1 Pi Zero W with camera module running Homebridge
1 Pi Zero W with camera module running HAP-python

The homebridge instance works perfectly, but now I want to add another Homekit instance using HAP-python.

HAP-python runs fine (on the second Pi) using `python busy-home.py`. 

However, doing `python camera-main.py` yields (after pairing):

```
`[accessory_driver] Paired with bfe57bae-cd06-4a0a-ba31-e3f86fa89396.
[zeroconf] Unknown error, possibly benign: KeyError('camera._hap._tcp.local.',)
Traceback (most recent call last):
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zeroconf.py", line 1871, in unregister_service
    del self.services[info.name.lower()]
KeyError: 'camera._hap._tcp.local.'
----------------------------------------
Exception happened during processing of request from ('192.168.178.46', 65309)
Traceback (most recent call last):
  File "/home/pi/berryconda3/lib/python3.6/socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/pi/.local/lib/python3.6/site-packages/pyhap/hap_server.py", line 853, in finish_request
    self, self.accessory_handler)
  File "/home/pi/.local/lib/python3.6/site-packages/pyhap/hap_server.py", line 143, in __init__
    super(HAPServerHandler, self).__init__(sock, client_addr, server)
  File "/home/pi/berryconda3/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/home/pi/berryconda3/lib/python3.6/http/server.py", line 420, in handle
    self.handle_one_request()
  File "/home/pi/berryconda3/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/home/pi/.local/lib/python3.6/site-packages/pyhap/hap_server.py", line 204, in dispatch
    getattr(self, self.HANDLERS[self.command][path])()
  File "/home/pi/.local/lib/python3.6/site-packages/pyhap/hap_server.py", line 539, in handle_pairings
    self._handle_add_pairing(tlv_objects)
  File "/home/pi/.local/lib/python3.6/site-packages/pyhap/hap_server.py", line 552, in _handle_add_pairing
    client_uuid, client_public)
  File "/home/pi/.local/lib/python3.6/site-packages/pyhap/accessory_driver.py", line 500, in pair
    self.update_advertisement()
  File "/home/pi/.local/lib/python3.6/site-packages/pyhap/accessory_driver.py", line 464, in update_advertisement
    self.advertiser.register_service(self.mdns_service_info)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zeroconf.py", line 1836, in register_service
    self.check_service(info, allow_name_change)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zeroconf.py", line 1952, in check_service
    raise NonUniqueNameException
zeroconf.NonUniqueNameException
----------------------------------------`
```

Somehow there seems to be a conflict with the other camera registered through homebridge?

Anyone seen this before?

**Comment by sbilly** [comment]
In my case it caused by name conflicts. I add `cache-entries-max=0` to  `avahi-daemon.conf` , and restart avahi-daemon, everything just work.

Please check this: https://github.com/lathiat/avahi/issues/117#issuecomment-442201162

**Comment by SanderGols-TomTom** [comment]
Thank you so much @sbilly this fixed it for me

**Comment by golles** [comment]
Thank you so much @sbilly, this has fixed it for me!
