### ISSUE TITLE
module 'asyncio' has no attribute 'SafeChildWatcher'

### ISSUE THREAD

**Issue by ThaFirstPaul** [ikalchev/HAP-python#218]
Upon running any HAP-pyhon service the following exception is caught:
```
[accessory_driver] Loading Accessory state from `busy_home.state`
[accessory_driver] Starting the event loop
[accessory_driver] Closed the event loop
Traceback (most recent call last):
  File "busy_home.py", line 104, in <module>
    driver.start()
  File "C:\Users\LuetzowP\Desktop\HAP-python-2.6.0\pyhap\accessory_driver.py", line 223, in start
    watcher = asyncio.SafeChildWatcher()
AttributeError: module 'asyncio' has no attribute 'SafeChildWatcher'
```
This error was reproduced on a clean install of Windows 10 (1903), with Python 3.8 and HAP-python v2.6.0
As far as I have tested, the error does not occur on Unix.

**Comment by rcarmo** [comment]
This has returned with Python 3.14
