### ISSUE TITLE
AssertionErrors referencing macOS machine

### ISSUE THREAD

**Issue by jjlawren** [ikalchev/HAP-python#230]
When using the Home Assistant [Homekit integration](https://www.home-assistant.io/integrations/homekit/), I occasionally get backtraces referencing HAP-python:
```
----------------------------------------
Exception happened during processing of request from ('192.168.2.2', 64896)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 880, in finish_request
    self, self.accessory_handler)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 151, in __init__
    super(HAPServerHandler, self).__init__(sock, client_addr, server)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 702, in recv_into
    data = self.recv(nbytes, flags)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 725, in recv
    block_length_bytes = self.socket.recv(self.LENGTH_LENGTH)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 713, in recv
    assert not flags and buflen > self.LENGTH_LENGTH
AssertionError
----------------------------------------
```
In the backtrace above, the 192.168.2.2 host is an unrelated macOS host running 10.15.3. That host has Homekit configured via the Home app but otherwise doesn't provide any Homekit services.

**Comment by bdraco** [comment]
@jjlawren Is this still happening in 0.108 ?

**Comment by jjlawren** [comment]
I haven't seen it since upgrading to 0.108.X.

**Comment by jjlawren** [comment]
@bdraco Sorry I spoke too soon. It happened again on 0.108.3 this morning.

**Comment by jjlawren** [comment]
Slightly different traceback:
```
----------------------------------------
Exception happened during processing of request from ('192.168.2.2', 53723)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 892, in finish_request
    self, self.accessory_handler)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 163, in __init__
    super(HAPServerHandler, self).__init__(sock, client_addr, server)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 714, in recv_into
    data = self.recv(nbytes or len(buffer), flags)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 738, in recv
    self.LENGTH_LENGTH, socket.MSG_WAITALL
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 724, in recv
    assert not flags and buflen > self.LENGTH_LENGTH
AssertionError
----------------------------------------
```

**Comment by bdraco** [comment]
It looks like the socket somehow got upgraded to the encrypted transport twice.  We probably need a lock somewhere

**Comment by bdraco** [comment]
@jjlawren Hopefully fixed by #249

**Comment by bdraco** [comment]
@jjlawren Has this issue gone away with Home Assistant 0.110?

**Comment by bdraco** [comment]
If not #253 is related as well (not yet published).  Should make it into 0.111

**Comment by jjlawren** [comment]
I haven't seen it since upgrading to 0.110. Hopefully this time it's gone for real. 👍

**Comment by jjlawren** [comment]
Just ran into it again on 0.111.2 😢 
```
----------------------------------------
Exception happened during processing of request from ('192.168.2.2', 64611)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 939, in finish_request
    self, self.accessory_handler)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 164, in __init__
    super(HAPServerHandler, self).__init__(sock, client_addr, server)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 757, in recv_into
    data = self.recv(nbytes or len(buffer), flags)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 781, in recv
    self.LENGTH_LENGTH, socket.MSG_WAITALL
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 767, in recv
    assert not flags and buflen > self.LENGTH_LENGTH
AssertionError
```

**Comment by bdraco** [comment]
Problem happens when we ask for 1 byte.

**Comment by bdraco** [comment]
@jjlawren  This branch should fix it https://github.com/bdraco/HAP-python/tree/handle_single_byte_buffer

**Comment by jjlawren** [comment]
Unclear if this is the same issue recurring, but it sure looks familiar:
```
----------------------------------------
Exception happened during processing of request from ('192.168.2.2', 52715)
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.8.3/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/homeassistant/.pyenv/versions/3.8.3/envs/prod383/lib/python3.8/site-packages/pyhap/hap_server.py", line 943, in finish_request
    self.RequestHandlerClass(request, client_address,
  File "/home/homeassistant/.pyenv/versions/3.8.3/envs/prod383/lib/python3.8/site-packages/pyhap/hap_server.py", line 164, in __init__
    super(HAPServerHandler, self).__init__(sock, client_addr, server)
  File "/home/homeassistant/.pyenv/versions/3.8.3/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/homeassistant/.pyenv/versions/3.8.3/lib/python3.8/http/server.py", line 429, in handle
    self.handle_one_request()
  File "/home/homeassistant/.pyenv/versions/3.8.3/lib/python3.8/http/server.py", line 395, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/home/homeassistant/.pyenv/versions/3.8.3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/homeassistant/.pyenv/versions/3.8.3/envs/prod383/lib/python3.8/site-packages/pyhap/hap_server.py", line 758, in recv_into
    data = self.recv(nbytes or len(buffer), flags)
  File "/home/homeassistant/.pyenv/versions/3.8.3/envs/prod383/lib/python3.8/site-packages/pyhap/hap_server.py", line 779, in recv
    block_length_bytes = self.socket.recv(
  File "/home/homeassistant/.pyenv/versions/3.8.3/envs/prod383/lib/python3.8/site-packages/pyhap/hap_server.py", line 768, in recv
    assert not flags and buflen
AssertionError
----------------------------------------
```
This is with HA 0.114.1 and HAP-python 3.0.0.

**Comment by eugenet8k** [comment]
I got this error as well. Interesting fact, at first I configured HASS HomeKit integration via Integrations UI. It was working smoothly for a few days, with absolutely no errors in the HASS log. Later, I decided that I want to configure HomeKit integration via YAML, so I removed the UI integration and created a new one in the configuration.yaml. After that, I started to get the mentioned errors. I tried to move back to Integrations UI but still having the same errors:

```
Exception happened during processing of request from ('10.0.1.22', 64035)
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/pi/.homeassistant-venv/lib/python3.8/site-packages/pyhap/hap_server.py", line 943, in finish_request
    self.RequestHandlerClass(request, client_address,
  File "/Users/pi/.homeassistant-venv/lib/python3.8/site-packages/pyhap/hap_server.py", line 164, in __init__
    super(HAPServerHandler, self).__init__(sock, client_addr, server)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/server.py", line 429, in handle
    self.handle_one_request()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/Users/pi/.homeassistant-venv/lib/python3.8/site-packages/pyhap/hap_server.py", line 270, in dispatch
    getattr(self, self.HANDLERS[self.command][path])()
  File "/Users/pi/.homeassistant-venv/lib/python3.8/site-packages/pyhap/hap_server.py", line 609, in handle_pairings
    self._handle_add_pairing(tlv_objects)
  File "/Users/pi/.homeassistant-venv/lib/python3.8/site-packages/pyhap/hap_server.py", line 638, in _handle_add_pairing
    self.accessory_handler.finish_pair()
  File "/Users/pi/.homeassistant-venv/lib/python3.8/site-packages/pyhap/accessory_driver.py", line 598, in finish_pair
    self.update_advertisement()
  File "/Users/pi/.homeassistant-venv/lib/python3.8/site-packages/pyhap/accessory_driver.py", line 530, in update_advertisement
    self.advertiser.unregister_service(self.mdns_service_info)
  File "/Users/pi/.homeassistant-venv/lib/python3.8/site-packages/zeroconf/__init__.py", line 2640, in unregister_service
    self.registry.remove(info)
  File "/Users/pi/.homeassistant-venv/lib/python3.8/site-packages/zeroconf/__init__.py", line 2375, in remove
    self._remove(info)
  File "/Users/pi/.homeassistant-venv/lib/python3.8/site-packages/zeroconf/__init__.py", line 2432, in _remove
    old_service_info = self.services[lower_name]
KeyError: 'hass bridge hp6v 124d33._hap._tcp.local.'
----------------------------------------
```

I got a number of errors from different IPs, and all of those seem to be Apple HomeKit hosts (TV etc.) that probably try to connect to HASS HomeKit Hub.
