### ISSUE TITLE
Two exceptions raised while driver starts up

### ISSUE THREAD

**Issue by hegga** [ikalchev/HAP-python#262]
I'm running version 2.8.4 of HAP-python and version 0.27.0 of zeroconf. While trying to pair with HomeKit, as the driver starts up the following traceback is thrown:
```

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 1312, in run
    reader.handle_read(socket_)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 1379, in handle_read
    self.zc.handle_query(msg, None, _MDNS_PORT)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2676, in handle_query
    service.text,
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 623, in __init__
    assert isinstance(text, (bytes, type(None)))
AssertionError

Future exception was never retrieved
future: <Future finished exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyhap/accessory_driver.py", line 287, in _do_start
    self.advertiser.register_service(self.mdns_service_info)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2374, in register_service
    self._broadcast_service(info)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2414, in _broadcast_service
    DNSText(info.name, _TYPE_TXT, _CLASS_IN | _CLASS_UNIQUE, info.other_ttl, info.text), 0
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 623, in __init__
    assert isinstance(text, (bytes, type(None)))
AssertionError
```

**Comment by bdraco** [comment]
Can you try downgrading to zeroconf 0.26.3?

**Comment by hegga** [comment]
Worked perfectly, thanks!

**Comment by bdraco** [comment]
@hegga Would you please open an issue here https://github.com/jstasiak/python-zeroconf/issues/new

The zeroconf team needs to know about this

**Comment by hegga** [comment]
[Two exceptions raised #269](https://github.com/jstasiak/python-zeroconf/issues/269)

**Comment by jstasiak** [comment]
There's been [a backwards incompatible change in zeroconf](https://github.com/jstasiak/python-zeroconf/commit/ab72aa8e5a6a83e50d24d7fb187e8fa8a549a847) and

```
        super().__init__(
            '_hap._tcp.local.',
            self.accessory.display_name + '._hap._tcp.local.',
            socket.inet_aton(self.state.address), self.state.port,
            0, 0, adv_data)
```

needs to become
```python
        super().__init__(
            '_hap._tcp.local.',
            self.accessory.display_name + '._hap._tcp.local.',
            self.state.port,
            0, 0, adv_data, addresses=[socket.inet_aton(self.state.address)])
```

or something similar (`addresses` is keyword-only).

**Comment by bdraco** [comment]
Thanks @jstasiak 

I sent a PR to use keywords which should work with 0.26.3 and 0.27 assuming the below looks right:

```
        super().__init__(
            '_hap._tcp.local.',
            name=self.accessory.display_name + '._hap._tcp.local.',
            port=self.state.port,
            weight=0,
            priority=0,
            properties=adv_data,
            addresses=[socket.inet_aton(self.state.address)]
        )
```

**Comment by jstasiak** [comment]
No worries. Yes, looks good! I'm wondering if maybe all `ServiceInfo`'s constructor parameters should become keyword-only at some point, there are too many of them.
