### ISSUE TITLE
List pairings is not implemented leading to pairing failures

### ISSUE THREAD

**Issue by bdraco** [ikalchev/HAP-python#290]
```
2020-11-02 20:03:29 DEBUG (Thread-57) [pyhap.hap_server] Request POST from address '('192.168.107.112', 49206)' for path '/pairings'.
2020-11-02 20:03:29 DEBUG (Thread-57) [pyhap.hap_server] finish_request: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyhap/hap_server.py", line 949, in finish_request
    self.RequestHandlerClass(request, client_address,
  File "/usr/local/lib/python3.8/site-packages/pyhap/hap_server.py", line 164, in __init__
    super(HAPServerHandler, self).__init__(sock, client_addr, server)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 429, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.8/site-packages/pyhap/hap_server.py", line 270, in dispatch
    getattr(self, self.HANDLERS[self.command][path])()
  File "/usr/local/lib/python3.8/site-packages/pyhap/hap_server.py", line 613, in handle_pairings
    raise ValueError
ValueError
2020-11-02 20:03:29 DEBUG (Thread-57) [pyhap.hap_server] Cleaning connection to ('192.168.107.112', 49206)
```
```
2020-11-02 20:25:35 DEBUG (Thread-43) [pyhap.hap_server] finish_request: Unknown pairing request type of 5 during pair verify
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyhap/hap_server.py", line 949, in finish_request
    self.RequestHandlerClass(request, client_address,
  File "/usr/local/lib/python3.8/site-packages/pyhap/hap_server.py", line 164, in __init__
    super(HAPServerHandler, self).__init__(sock, client_addr, server)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 429, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.8/site-packages/pyhap/hap_server.py", line 270, in dispatch
    getattr(self, self.HANDLERS[self.command][path])()
  File "/usr/local/lib/python3.8/site-packages/pyhap/hap_server.py", line 613, in handle_pairings
    raise ValueError("Unknown pairing request type of %s during pair verify" % (request_type))
ValueError: Unknown pairing request type of 5 during pair verify
```

**Comment by bdraco** [comment]
Was fixed in 3.3.0
