### ISSUE TITLE
Connection get dropped if fetching a snapshot fails

### ISSUE THREAD

**Issue by bdraco** [ikalchev/HAP-python#291]
```
2020-11-02 23:33:28 DEBUG (Thread-104) [pyhap.hap_server] finish_request: Unable to get image
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyhap/hap_server.py", line 949, in finish_request
    self.RequestHandlerClass(request, client_address,
  File "/usr/local/lib/python3.8/site-packages/pyhap/hap_server.py", line 164, in __init__
    super(HAPServerHandler, self).__init__(sock, client_addr, server)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 429, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.8/site-packages/pyhap/hap_server.py", line 270, in dispatch
    getattr(self, self.HANDLERS[self.command][path])()
  File "/usr/local/lib/python3.8/site-packages/pyhap/hap_server.py", line 664, in handle_resource
    image = self.accessory_handler.accessory.get_snapshot(image_size)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 544, in get_snapshot
    return acc.get_snapshot(info)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_cameras.py", line 450, in get_snapshot
    asyncio.run_coroutine_threadsafe(
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 164, in async_get_image
    raise HomeAssistantError("Unable to get image")
homeassistant.exceptions.HomeAssistantError: Unable to get image

```

We probably should send a 500 error here.

**Comment by bdraco** [comment]
Was fixed in 3.1.0
