### ISSUE TITLE
Orjson, requires a 64-bit Python with>3.8.5+and<3.9

### ISSUE THREAD

**Issue by fwebcc** [ikalchev/HAP-python#439]
Orjson, requires a 64-bit Python with>3.8.5+and<3.9
Cannot be used on embedded devices such as routers and some ARM devices
You can remove this library and use Json directly?

**Comment by bdraco** [comment]
Json is too slow to meet iOS 16 requirements 

orjson builds just fine on 32bit.  Home assistant is using it.

**Comment by bdraco** [comment]
There are 32 bit wheels at:

https://pypi.org/project/orjson/#files
And musl ones here
https://wheels.home-assistant.io/musllinux/

**Comment by fwebcc** [comment]
Thank you for your reply. I have tried, but I am using Asus88u CPU with armhf architecture, which unfortunately does not support it

**Comment by bdraco** [comment]
armhf can mean different things depending on the os vendor.  If its ARMv6 + musl you can use https://wheels.home-assistant.io/musllinux/orjson-3.8.10-cp311-cp311-musllinux_1_2_armv6l.whl

**Comment by fwebcc** [comment]
loog@RT-AC88U-2C70:/tmp/mnt/fwebcc/tmp#  pip3 install orjson-3.8.10-cp311-cp311-musllinux_1_2_armv6l.whl
ERROR: orjson-3.8.10-cp311-cp311-musllinux_1_2_armv6l.whl is not a supported wheel on this platform.

**Comment by bdraco** [comment]
Are you using glibc?

**Comment by bdraco** [comment]
That wheel is for musl + python 3.11

**Comment by bdraco** [comment]
for python 3.10 https://wheels.home-assistant.io/musllinux/orjson-3.8.10-cp310-cp310-musllinux_1_2_armv6l.whl

**Comment by fwebcc** [comment]
Thank you. I'll try upgrading to Python 3.10 later now python3.9

**Comment by fwebcc** [comment]
libc-2.23.so

**Comment by bdraco** [comment]
You need glibc wheels.  It doesn't look like anyone is already building thoose

You can fork orjson and add whatever `qemu` arch here
https://github.com/ijl/orjson/blob/c2514ab9ecdb9d42945f3fc6e18475b88bef8ec2/.github/workflows/linux.yaml#L213

And than use github actions to build them or send them a PR

**Comment by fwebcc** [comment]
https://wheels.home-assistant.io/alpine-3.14/armhf/HAP_python-4.4.0-py3-none-any.whl
It can run

**Comment by bdraco** [comment]
I opened a test PR to see if armv6 can be built that way as well 
https://github.com/bdraco/orjson/pull/1
It will take a few hours to get a result

**Comment by RikJm** [comment]
Hi there, first of all thanks a lot for this amazing library, I am truly awed on what you have accomplished here. Also, apologies if my error is not related to this issue but it seemed to me after quite a bit of googling that it might be a 32/64 bit issue as well.

I am trying to use this on a Raspberry Pi Zero W (ver 1.3) with Raspberry Pi OS Lite (32bit) port of Debian Bookworm with no desktop environment installed - _It is worth mentioning everything works fine on my Raspberry Pi 3 with a 64bit OS._

After failing on my first go, I managed to install all the requirements one by one without issues on my venv, orjson required me to install rust manually but that did the trick.

`(PythonHAP) rik@PiZeroIRHat:~/.hap-python $ pip list
Package                    Version
-------------------------- -------
async-timeout              5.0.1
base36                     0.1.1
cffi                       1.17.1
chacha20poly1305-reuseable 0.13.2
cryptography               44.0.0
h11                        0.14.0
HAP-python                 4.9.2
ifaddr                     0.2.0
orjson                     3.10.14
pip                        23.0.1
pycparser                  2.22
PyQRCode                   1.2.1
setuptools                 66.1.1
zeroconf                   0.137.2`

The issue however persists when running my python script, it fails importing the AccessoryDriver due to what seems to be a Cryptography error : 

`(PythonHAP) rik@PiZeroIRHat:~/.hap-python $ python hap-python.py 
Traceback (most recent call last):
  File "/home/rik/.hap-python/hap-python.py", line 8, in <module>
    from pyhap.accessory_driver import AccessoryDriver
  File "/home/rik/PythonHAP/lib/python3.11/site-packages/pyhap/accessory_driver.py", line 52, in <module>
    from pyhap.encoder import AccessoryEncoder
  File "/home/rik/PythonHAP/lib/python3.11/site-packages/pyhap/encoder.py", line 9, in <module>
    from cryptography.hazmat.primitives import serialization
  File "/home/rik/PythonHAP/lib/python3.11/site-packages/cryptography/hazmat/primitives/serialization/__init__.py", line 7, in <module>
    from cryptography.hazmat.primitives._serialization import (
  File "/home/rik/PythonHAP/lib/python3.11/site-packages/cryptography/hazmat/primitives/_serialization.py", line 10, in <module>
    from cryptography.hazmat.primitives.hashes import HashAlgorithm
  File "/home/rik/PythonHAP/lib/python3.11/site-packages/cryptography/hazmat/primitives/hashes.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import openssl as rust_openssl
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory`

Is this a 32 bit issue? if so, is there a way I could fix it myself locally compiling cryptography? I did read somewhere the piwheels were wrong, however they also said they fixed that on version 44.0.0... which left me clueless.

Thanks again for all your help and incredible work!!

**Comment by bdraco** [comment]
Home Assistant ships 32bit crypto wheels so it's likely a problem with piwheels or a missing OpenSSL lib

**Comment by RikJm** [comment]
@bdraco , you were absolutely right, I have no idea how I missed this on the zero, both the pi3 were working fine so I assumed the zero would be as well. 

The issue was indeed fixed by simply doing a simple. >

 `sudo apt install libssl1.1`

I leave this here in case anyone finds themselves making the same oversight. Thank you very much!
